"use client";

import "../../globals.css";
import { Inter } from "next/font/google";

import CheckoutHeader from "@/components/CheckoutFlow/Checkout.Header";
import CheckoutFooter from "@/components/CheckoutFlow/Checkout.Footer";
import { SessionProvider, signIn, signOut, useSession } from "next-auth/react";
import { Session } from "next-auth";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth/next";
import type { AppProps } from "next/app";
import Providers from "@/app/provider/providers";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const CheckoutLayout = ({
  children,

  // Component,
  // pageProps,
}: {
  children: React.ReactNode;

  // Component: AppProps["Component"];
  // pageProps: AppProps["pageProps"];
}) => {
  //const { data: session1, status } = useSession()
  return (
    <html lang="en">
      <body className="flex flex-col h-screen leading-normal tracking-normal bg-gray-100">
        {/* <SessionProvider session={pageProps.session}> */}
        <Providers>
          <CheckoutHeader />
          <main className=" max-w-[1440px] mx-auto mb-auto relative  border-2 border-red-500">
            {children}
          </main>
          <CheckoutFooter />
          </Providers>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}

export default CheckoutLayout;
