"use client";

import "../../globals.css";
import { Inter } from "next/font/google";

import CheckoutHeader from "@/components/CheckoutFlow/Checkout.Header";
import CheckoutFooter from "@/components/CheckoutFlow/Checkout.Footer";
import { SessionProvider, signIn, signOut, useSession } from "next-auth/react";
import { Session } from "next-auth";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth/next"

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  
  return (
    <html lang="en">
      <body className="flex flex-col h-screen leading-normal tracking-normal bg-gray-100">
        <SessionProvider session={session}>
          <CheckoutHeader />
          <main className=" max-w-[1440px] mx-auto mb-auto relative  border-2 border-red-500">
            {children}
          </main>
          <CheckoutFooter />
        </SessionProvider>
      </body>
    </html>
  );
}
